# ~/.bash_profile

# Tmux already has this loaded
export GOPATH="$HOME/go"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export PATH="$HOME/bin:$GOPATH/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/curl/bin:$PATH"

export VISUAL="nvim"
export MAVEN_OPTS="-Xmx4096m -DskipTests=true"
export RERUN_MODULES="$HOME/projects/rerun_modules"

# Source bashrc
# shellcheck disable=SC1090
source "$HOME/.bashrc"

