#
# ~/.bashrc
#

if [[ -f ~/.dircolors ]] ; then
  eval $(dircolors -b ~/.dircolors)
elif [[ -f /etc/DIR_COLORS ]] ; then eval $(dircolors -b /etc/DIR_COLORS)
fi

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias dir="dir --color=auto"
alias grep="grep --color=auto"
alias dmesg='dmesg --color'
alias mvn="mvn -T 1C"
alias cb="xclip -selection clipboard"

PS1='[\u@\h \W]\$ '

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# cd and ls in one
cl() {
  dir=$1
  if [[ -z "$dir" ]]; then
    dir=$HOME
  fi
  if [[ -d "$dir" ]]; then
    cd "$dir"
    ls
  else
    echo "bash: cl: '$dir': Directory not found"
  fi
}

# Start off with a blinking cursor
#echo -ne "\e[0 q"

# Disable Flow-control so these keys are available for mapping C-S/C-Q
stty -ixon

# Don't show ^C character
stty -echoctl

function r() {
if [[ -n $TMUX ]]; then
  NEW_SSH_AUTH_SOCK=`tmux showenv|grep ^SSH_AUTH_SOCK|cut -d = -f 2`
  if [[ -n $NEW_SSH_AUTH_SOCK ]] && [[ -S $NEW_SSH_AUTH_SOCK ]]; then
    SSH_AUTH_SOCK=$NEW_SSH_AUTH_SOCK
  fi
fi
}

function docker_id {
  docker ps | grep "$1" | cut -f1 -d" "
}

alias did=docker_id

function de {
   container_id=$(docker_id "$1")
   c=${2:-"bash -l"}
   docker exec -it -u root "$container_id" $c
}

# Start off with a blinking cursor
#echo -ne "\e[0 q"

#source ~/projects/rerun/rerun-*/etc/bash_completion.sh
#export CDPATH=".:~/projects"

export VISUAL="nvim"
export MAVEN_OPTS="-Xmx2048m -DskipTests=true"
export RERUN_MODULES="$HOME/projects/rerun_modules"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash ] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.bash
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash ] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.bash
